config:
  namespace: eyetap
  clusterName: cluster
  cors: ''
  secrets:
    jwt: ''
    debug: ''
  db: 
    url: "eyetap-pg.{{ .Values.config.namespace }}.svc.{{ .Values.config.clusterName }}.local:5432/{{ .Values.config.db.db }}"
    username: eyetap
    db: eyetap
    password: eyetap

app:
  image:
    repository: ghcr.io/eye-tap/backend
    tag: latest
    pullPolicy: Always

  name: eyetap-backend
  port: 8080
